2020-08-16 12:05:01,251 INFO: Microblog startup [in C:\Users\ASUS\Desktop\Python\Flask\microblog\app\__init__.py:44]
2020-08-16 12:13:33,766 INFO: Microblog startup [in C:\Users\ASUS\Desktop\Python\Flask\microblog\app\__init__.py:44]
2020-08-16 14:01:02,425 INFO: Microblog startup [in C:\Users\ASUS\Desktop\Python\Flask\microblog\app\__init__.py:44]
2020-08-16 14:01:13,577 INFO: Microblog startup [in C:\Users\ASUS\Desktop\Python\Flask\microblog\app\__init__.py:44]
2020-08-16 14:32:04,541 INFO: Microblog startup [in C:\Users\ASUS\Desktop\python\flask\microblog\app\__init__.py:44]
2020-08-16 15:01:10,988 INFO: Microblog startup [in C:\Users\ASUS\Desktop\Python\Flask\microblog\app\__init__.py:44]
2020-08-16 15:01:18,626 INFO: Microblog startup [in C:\Users\ASUS\Desktop\Python\Flask\microblog\app\__init__.py:44]
2020-08-16 15:04:18,247 INFO: Microblog startup [in C:\Users\ASUS\Desktop\Python\Flask\microblog\app\__init__.py:44]
2020-08-16 15:04:22,280 INFO: Microblog startup [in C:\Users\ASUS\Desktop\Python\Flask\microblog\app\__init__.py:44]
2020-08-16 15:06:47,453 INFO: Microblog startup [in C:\Users\ASUS\Desktop\Python\Flask\microblog\app\__init__.py:44]
2020-08-16 16:05:47,274 INFO: Microblog startup [in C:\Users\ASUS\Desktop\Python\Flask\microblog\app\__init__.py:44]
2020-08-16 16:05:55,987 ERROR: Exception on /explore [GET] [in c:\users\asus\desktop\python\flask\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\asus\desktop\python\flask\microblog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\asus\desktop\python\flask\microblog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\asus\desktop\python\flask\microblog\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\asus\desktop\python\flask\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\asus\desktop\python\flask\microblog\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\asus\desktop\python\flask\microblog\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\asus\desktop\python\flask\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\ASUS\Desktop\Python\Flask\microblog\app\routes.py", line 36, in explore
    return render_template('index.html', title='Explore', posts=posts)
  File "c:\users\asus\desktop\python\flask\microblog\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\asus\desktop\python\flask\microblog\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\asus\desktop\python\flask\microblog\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\asus\desktop\python\flask\microblog\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\asus\desktop\python\flask\microblog\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\ASUS\Desktop\Python\Flask\microblog\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\ASUS\Desktop\Python\Flask\microblog\app\templates\base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\ASUS\Desktop\Python\Flask\microblog\app\templates\index.html", line 6, in block "content"
    {{ form.hidden_tag() }}
  File "c:\users\asus\desktop\python\flask\microblog\venv\lib\site-packages\jinja2\environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2020-08-16 16:06:11,495 ERROR: Exception on /explore [GET] [in c:\users\asus\desktop\python\flask\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\asus\desktop\python\flask\microblog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\asus\desktop\python\flask\microblog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\asus\desktop\python\flask\microblog\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\asus\desktop\python\flask\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\asus\desktop\python\flask\microblog\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\asus\desktop\python\flask\microblog\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\asus\desktop\python\flask\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\ASUS\Desktop\Python\Flask\microblog\app\routes.py", line 36, in explore
    return render_template('index.html', title='Explore', posts=posts)
  File "c:\users\asus\desktop\python\flask\microblog\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\asus\desktop\python\flask\microblog\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\asus\desktop\python\flask\microblog\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\asus\desktop\python\flask\microblog\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\asus\desktop\python\flask\microblog\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\ASUS\Desktop\Python\Flask\microblog\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\ASUS\Desktop\Python\Flask\microblog\app\templates\base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\ASUS\Desktop\Python\Flask\microblog\app\templates\index.html", line 6, in block "content"
    {{ form.hidden_tag() }}
  File "c:\users\asus\desktop\python\flask\microblog\venv\lib\site-packages\jinja2\environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2020-08-16 16:20:24,936 ERROR: Exception on /explore [GET] [in c:\users\asus\desktop\python\flask\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\asus\desktop\python\flask\microblog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\asus\desktop\python\flask\microblog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\asus\desktop\python\flask\microblog\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\asus\desktop\python\flask\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\asus\desktop\python\flask\microblog\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\asus\desktop\python\flask\microblog\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\asus\desktop\python\flask\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\ASUS\Desktop\Python\Flask\microblog\app\routes.py", line 36, in explore
    return render_template('index.html', title='Explore', posts=posts)
  File "c:\users\asus\desktop\python\flask\microblog\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\asus\desktop\python\flask\microblog\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\asus\desktop\python\flask\microblog\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\asus\desktop\python\flask\microblog\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\asus\desktop\python\flask\microblog\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\ASUS\Desktop\Python\Flask\microblog\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\ASUS\Desktop\Python\Flask\microblog\app\templates\base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\ASUS\Desktop\Python\Flask\microblog\app\templates\index.html", line 6, in block "content"
    <form action="" method="post">
  File "c:\users\asus\desktop\python\flask\microblog\venv\lib\site-packages\jinja2\environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
